services:
  - type: web
    name: evolution-api
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTHENTICATION_API_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: evolution-db
          property: connectionString
      - key: REDIS_URI
        fromService:
          type: redis
          name: evolution-redis
          property: connectionString

databases:
  - name: evolution-db
    plan: free

# In Blueprints, the section MUST be named 'redis'
redis:
  - name: evolution-redis
    plan: free
    ipAllowList: [] # This allows the API to talk to Redis
